endpoints:
    session: https://api.crunchyroll.com/get_upsell_data.0.json
    login: https://api.crunchyroll.com/login.1.json
    seasons: 'https://beta-api.crunchyroll.com/cms/v2{bucket}/seasons'
    episodes: 'https://beta-api.crunchyroll.com/cms/v2{bucket}/episodes'
    movies: 'https://beta-api.crunchyroll.com/cms/v2{bucket}/movies'
    metadata: 'https://beta-api.crunchyroll.com/cms/v2{bucket}/movie_listings/{title_id}'
    streams: 'https://beta-api.crunchyroll.com/cms/v2{bucket}/videos/{media_id}/streams'
    # streams: 'https://beta-api.crunchyroll.com/cms/v2/{country}/M3/crunchyroll/videos/{title_id}/streams'
    token: 'https://beta-api.crunchyroll.com/auth/v1/token'
    bucket: 'https://beta-api.crunchyroll.com/index/v2'
    drm_auth: 'https://beta-api.crunchyroll.com/drm/v1/auth'
    license: 'https://cr-license-proxy.prd.crunchyrollsvc.com/v1/license/widevine'
    chapters: 'https://static.crunchyroll.com/datalab-intro-v2/{}.json'
    credits: 'https://static.crunchyroll.com/skip-events/production/{}.json'
    objects: 'https://beta-api.crunchyroll.com/content/v2/cms/objects/{media_id}'
    streams_stop: https://cr-play-service.prd.crunchyrollsvc.com/v1/token/{guid}/{token}
    streams_start: https://cr-play-service.prd.crunchyrollsvc.com/v1/{id}/tv/android_tv/play
    #streams_start: https://cr-play-service.prd.crunchyrollsvc.com/v1/{id}/web/firefox/play